version: '3.8'

services:
  # Database Storage Layer Engine
  arl-db:
    image: mysql:8.0
    container_name: arl_mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: arl_db
      MYSQL_ROOT_PASSWORD: Phua@0809
<<<<<<< HEAD
=======
      # modify the password, make sure same as the MySql psw
>>>>>>> c6b9ef8c7328639b28d79cd09143d093fcdf8ae7
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - arl-network
    healthcheck:
<<<<<<< HEAD
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pPhua@0809"]
=======
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pPhua@0809"]   # change password
>>>>>>> c6b9ef8c7328639b28d79cd09143d093fcdf8ae7
      interval: 10s
      timeout: 5s
      retries: 5

  # Spring Boot Backend REST Application
  arl-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arl_springboot_backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://arl-db:3306/arl_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
<<<<<<< HEAD
=======
      # change password
>>>>>>> c6b9ef8c7328639b28d79cd09143d093fcdf8ae7
      - SPRING_DATASOURCE_PASSWORD=Phua@0809
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      arl-db:
        condition: service_healthy
    networks:
      - arl-network

  # Angular Tailwind Frontend Interface Web Server
  arl-frontend:
    build:
      context: ./arl-frontend
      dockerfile: Dockerfile
    container_name: arl_angular_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - arl-backend
    networks:
      - arl-network

volumes:
  db_data:

networks:
  arl-network:
    driver: bridge
