spring.application.name=assignment1-group4

spring.datasource.url=jdbc:mysql://localhost:3306/arl_db
spring.datasource.username=root
# spring.datasource.password=Phua@0809

# new password for Amirah, QA Tester
#spring.datasource.password=Ajax-Amirah06
spring.datasource.password=1602

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update